# Generated by Django 5.2.15 on 2026-09-28 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anime_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('mal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
    ]
